# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(blank=True, max_length=250)),
                ('activity', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(default='other', max_length=250)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
