# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='created',
        ),
    ]
