# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20170405_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('category', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
    ]
