# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20170405_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripitem',
            name='trip_id',
        ),
        migrations.DeleteModel(
            name='TripItem',
        ),
    ]
