# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagging',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
