# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggings', '0004_auto_20170407_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='created',
        ),
    ]
