# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0005_auto_20170406_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('suggested_category', models.CharField(max_length=250)),
                ('status', models.CharField(default='False', max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
