# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripitem',
            old_name='suggested_category',
            new_name='category',
        ),
    ]
