# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('suggested_category', models.CharField(blank=True, default='', max_length=250)),
                ('picture', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
