# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170405_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='suggested_category',
            field=models.CharField(max_length=250),
        ),
    ]
