# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20170405_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='False', max_length=50),
        ),
    ]
